### ISSUE TITLE
Empty array when visualizing some of OakInk-Shape data

### ISSUE THREAD

**Issue by SupreethN** [lixiny/OakInk#2]
I am trying to run ```viz_oakink_shape.py```. But for some categories such as ```apple``` with intents ```[use, hold, liftup, handover]``` and split ```train```, I get the following error: What are some possible reasons for this? Maybe there is no hand present for grasp?

```Traceback (most recent call last):
  File "viz_oakink_shape.py", line 53, in <module>
    main(arg)
  File "viz_oakink_shape.py", line 28, in main
    oi_shape = OakInkShape(category=category, intent_mode=intent, data_split=split)
  File "/home/snarasimhaswamy/OakInk/oikit/oi_shape/oi_shape.py", line 126, in __init__
    batch_hand_shape = torch.from_numpy(np.stack(batch_hand_shape))
  File "<__array_function__ internals>", line 180, in stack
  File "/opt/conda/envs/oakink/lib/python3.8/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by KailinLi** [comment]
Currently, we randomly select 80% of objects for training, 10% for validation, and the rest 10% for testing. The apple category has only one CAD model, the C90001. And unfortunately, this object is randomly assigned to the **test set**. Therefore, you can not find any grasps of an apple in the **train** split.
You can use `OakInkShape(category="apple", data_split="test")` or just `OakInkShape(category="apple")` to visualize the grasps of the apple.

**Comment by SupreethN** [comment]
Thank you for the quick response!

**Comment by PostResPerditas** [comment]
I'm trying to run viz_oakink_shape.py too.
But to me, this error occurs in all categories. :(

**Comment by KailinLi** [comment]
Sorry to hear about the issue.
This typically shouldn’t happen.
Please ensure `OAKINK_DIR` is set correctly and the dataset is extracted and organized as per the documentation.
<img width="218" alt="截屏2024-09-11 14 15 47" src="https://github.com/user-attachments/assets/33025765-261d-4089-b008-324b42d358b4">
