### ISSUE TITLE
How to get the MANO hand faces/ triangles for the image data?

### ISSUE THREAD

**Issue by SupreethN** [lixiny/OakInk#3]
Dear authors,

I am trying to obtain hand faces/ triangles for the OakInk-Image part. I see that you already have code to do this for the OakInk-Shape [here ](https://github.com/lixiny/OakInk/blob/main/oikit/oi_shape/utils.py#L103). How can I obtain this for the image part data? Should I just add a simple class method [here](https://github.com/lixiny/OakInk/blob/main/oikit/oi_image/oi_image.py#L25) that takes MANO hand shape and hand pose as input to the ```ManoLayer``` and access ```ManoLayer.th_faces```?

Thanks

**Comment by lixiny** [comment]
Yes, you can access the MANO hand faces through a static ManoLayer object.

Current the **oikit** only provide the bare usage: load image, load annotations, and visualize.
Feel free to customize.

Thanks.

**Comment by SupreethN** [comment]
Thanks!
