### ISSUE TITLE
Attribute of object inconsistent with paper?

### ISSUE THREAD

**Issue by tianhaowuhz** [lixiny/OakInk#6]
I am seraching for the attribute of object. However, in the metaV2.zip, I can only find attribute such as "handled" without attribute such as "loosen" in there, so where is the attribute information of every object claimed in Appx Table 7 ?

**Comment by lixiny** [comment]
Thank you for your interest in our work.

It is worth clarifying that the attributes in the metaV2 files (in the OakInk-Shape dataset) are what we use to name the different object models and to retrieve objects.
It is different from the "attribute" mentioned in the object affordance knowledge (Oak) base.

Currently, the public data does not contain the part segmentations and attributes mentioned in the Oak base.

If you are interested in these parts, we will post them to the public link next semester, after the end of the Lunar New Year vacation.

**Comment by tianhaowuhz** [comment]
Thank you so much for your reply. I do interesed in these parts, it would be great helpful if you can post them! So it would be posted on February (not very sure what is the exact time of the end of your vacation)?

**Comment by lixiny** [comment]
Hi, 
the Oak Base, containing the object parts segmentation and attribute, is now publicly available. 

Download at [oakink.net](https://oakink.net)
Demo usage at [demo_oak_base.py](https://github.com/oakink/OakInk/blob/main/scripts/demo_oak_base.py)

Lixin

**Comment by tianhaowuhz** [comment]
Thank you so much!
