### ISSUE TITLE
Question about contactpose model

### ISSUE THREAD

**Issue by tianhaowuhz** [lixiny/OakInk#7]
Hi, recetnly I am trying to use the dataset in simulator. However, I found the data for contactpose only has pointcloud, and no mesh which can not be used in simulator to load object. I also tried to match the original contactpose object model, but it has slight rotation which is hard to match exactly. Thus, I am wondering can you public the processed object model related to contactpose, Thank you so much!

**Comment by tianhaowuhz** [comment]
I also tried to convert pointcloud to mesh. However, some of the mesh quality is very bad.

**Comment by lixiny** [comment]
Hi, the contactpose object models we provided (in `OakInkObjectsV2.zip`) are triangle meshes.  

for example: 
the object model:  `OakInkObjectsV2/contactpose_camera/align/camera.ply` can be loaded via MeshLab as:


![截屏2023-06-07 21 32 41](https://github.com/oakink/OakInk/assets/32672902/5b576a09-5756-4a13-ad72-30a5d137e72f)

**Comment by tianhaowuhz** [comment]
I am sorry I didn't check that, thank you  for your reply!

**Comment by tianhaowuhz** [comment]
Hi, I check other ply file for contactpose, and note some object is not correct?  The object in following picture is CUP.
![Screenshot from 2023-06-08 09-05-54](https://github.com/oakink/OakInk/assets/43113029/f4d666a3-6e1e-4671-8106-e1b9aef48ab2)

**Comment by tianhaowuhz** [comment]
By the way, what is the difference between "algin" and "algin ds"?

**Comment by lixiny** [comment]
The `align` model aligns the objects' canonical system within a certain OakInk category. The `align_ds` model downsamples the original mesh of an object to reduce the number of vertices and the surface for quicker computing. We have ensured that the downsampled model is watertight, thanks to ManifoldPlus. Therefore, it can be used to compute the SDF, but it's worth noting that some of the downsampled objects may have different geometry compared to the original ones.

**Comment by tianhaowuhz** [comment]
Thank you  so much !
