### ISSUE TITLE
The data correspondence between shape and image

### ISSUE THREAD

**Issue by wyl2077** [lixiny/OakInk#9]
Hi,

I'm interested in understanding how to locate the RGB image that corresponds to a specific grasp pose within the shape dataset. For instance, I'm looking to find the RGB image associated with the grasp pose detailed in "./shape/oakink_shape_v2/apple/C90001/461d0e1f41/hand_param.pkl". I noticed that the source file is indicated as "pass1E/C90001_0004_0001_0007/2021-10-09-14-39-54/dom.pkl". However, it appears that I need the actual frame to access the corresponding image from directory “./image/stream_release_v2/C90001_0004_0001_0007/2021-10-09-14-39-54/”. Could you provide guidance on how to proceed with this?
![Snipaste_2024-03-11_19-39-39](https://github.com/oakink/OakInk/assets/69098468/2e70f501-da80-4ca1-8d2e-c465d2216033)

Thanks a lot.

**Comment by lixiny** [comment]
It's unfortunate, but the exact frame corresponding to this grasping pose might be irretrievable. 

During the development of this dataset, we manually selected a dominant frame from each sequence, which we labeled as `dom`.pkl. Regrettably, we neglected to record the frame ID for these selections.
